### ISSUE TITLE
Question regarding connecting users Namespaces and Rooms

### ISSUE THREAD

**Issue by oasker** [jTronixDevelopment/projectX#25]
So my understanding is that to join a user to a game the following steps should take place, lmk if I dont get it right.
1. At home page have user select which game they want to play
2. Ask if they want to start a new game or join existing one
    a. To create a new game -> generate unique code to use for room key
    b. To join existing game -> display text entry field for user to enter room code
3. Submit the game namespace and room code to join user to their game

**Comment by johnson2500** [comment]
I will show you tonight on our call. But the way I think it should work is as follows. 
1) The Actual host of the game (Apple TV, Chromecast, etc...) will provide a code on the screen. 
2) The client on there phone will enter the code which will determine what game they are playing.
So game creation is now going to be handled by the TV rather then the user, which will simplify alot.
