### ISSUE TITLE
Create Error Handling

### ISSUE THREAD

**Issue by johnson2500** [jTronixDevelopment/projectX#27]
*Create Error handling/Input Validation *

**Sever Side** 
***File***
```sh
TBD
```
***Task***
```sh
On msg Recieved from client
Ensure always the msg object passed exists.
Ensure that object contain valid code.
Ensure the input had no special Characters, numbers, and is upper case. 
```

**Client Side** 
***File***
```sh
TBD
```
***Task***
```sh
Before Msg is submitted make sure the roomCode: 
Is of the correct length (5).
The first letter contains a valid namespace code.
Contains no Numbers.
Is set to upper Case
```

**Comment by oasker** [comment]
what will the first letter of the namespace codes be?

**Comment by johnson2500** [comment]
@oasker  The name spaces are set in stone, it will be the room codes that will change according to each game. Each with a unique letter to determine which room. You choose what you want

**Comment by johnson2500** [comment]
@oasker @jTronixDevelopment/questions Are you ready for this to be merged
