### ISSUE TITLE
Create Random Number Generator

### ISSUE THREAD

**Issue by johnson2500** [jTronixDevelopment/projectX#8]
**Create Random Number Generator in the gameManager.js file.** 

This should return a unique Set of Characters. 
```sh 
methodName{
    return 5 character unique random number
}
```
This Does have dependencies. 
Take a look at the socket.io built in functionality that provides already unique identifiers for each socket. Which could also be leveraged with out make our own.

**Comment by oasker** [comment]
I didnt see that in the socket docs but shortid seems pretty handy. We won’t have to create a check for duplicate ids either. https://www.npmjs.com/package/shortid
